version: '3.8' # Version 3.8 is quite new and should work

# services:
#   app: # The name of the service, can be anything
#     image: hello-front-dev # Declares which image to use
#     build: . # Declares where to build if image is not found
#     ports: # Declares the ports to publish
#       - 3000:3000

services:
  app:
    image: hello-front-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
    container_name: hello-front-dev1

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app # wait for the frontend container to be started


  # debug-helper:
  #   image: busybox
# execute the following command to start the container
# docker compose up
